# Generated by Django 4.2.2 on 2023-06-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
